.\" .UC 4
.TH "HCAL" "1" "2 Mar 2005" "Yaacov Zamir" "libhdate"
.SH "NAME"
hcal \- displays a Hebrew / Gregorian calendar
.PP 
.SH "SYNOPSIS"
.B hcal [\-hdi]
[ [ mm ] yyyy ]
.PP
.SH "DESCRIPTION"
.B Hcal
prints a calendar with both Gregorian and Hebrew dates for the
specified Gregorian month or, if no month is specified, for the
whole Gregorian year. If no arguments are given, it prints the
current month's calendar.
.PP
.B INPUTTING A HEBREW DATE:
If the year provided is greater than 3000,
.B hdate
will interpret the given date as a Hebrew date, and will display the calendar of the corresponding Gregorian month(s). Hebrew months are expected to be passed as numbers 1-12 for Tishrei - Elul 12; Adar I and Adar II are expected to be passed as months 13 and 14.
.PP
.B Hcal
and
.B Hdate
are part of the package
.B libhdate
, a small C,C++ library for Hebrew dates, holidays, and reading
sequences (parashiot). It uses the source code from Amos Shapir's
"hdate" package, as fixed and patched by Nadav Har'El. The Torah
reading sequence tables were contributed by Zvi Har'El.
.PP 
.SH "OPTIONS"
.B \-h    
Print output in html format.
.PP
.B \-d    
Use diaspora reading and holidays.
.PP
.B \-i    
Use external css file "./hcal.css".
.PP
.El
.PP
.SH "HOLIDAYS"
.PP
Holidays are depicted by a change in the symbol separating a day's
Gregorian and Hebrew dates, as follows:

/ Regular day

+ Yom Tov (plus Yom Kippur)

* Erev Yom Kippur

~ Hol HaMoed

! Hanuka and Purim

@ Tzomot

# Independance day and Yom Yerushalaim

$ Lag BaOmer ,Tu BeAv, Tu BeShvat

% Tzahal and Holocaust memorial days

^ National days
.PP
.SH "SEE ALSO"
date(1), cal(1), hdate(1), hebcal(1), remind(1), hdate.h(3), hdate_struct(3)
.SH "AUTHORS"
Boruch Baum 2011

Yaacov Zamir 2005-2010, text copied from Amos Shapir's hdate man file.
