.\" .UC 4
.TH "HDATE" "1" "2011-11-21" "Linux" "libhdate"
.SH "NAME"
hcal \- displays a Hebrew / Gregorian calendar
.PP 
.SH "SYNOPSIS"
.B hcal
[options]
.RI [\-l \ latitude \ \-L \ longitude \ [-z \ nn ]]
[[[dd] mm] yyyy]
.PP
.SH "DESCRIPTION"
.B hcal
prints a calendar with both Gregorian and Hebrew dates for the
specified Gregorian month or, if no month is specified, for the
whole Gregorian year. If no arguments are given, it prints the
current month's calendar.
.PP
.B LOCATION: 
If you want 
.B hcal
to display accurate Shabbat times, and to accurately advance the Hebrew 'today's date' indicator at sunset, 
.B hcal
requires location and time zone information in order to make astronomical calculations for a given date. If you don't provide ANY such information, 
.B hcal
uses your computer's local time zone information as an indicator, and either picks a city in that time zone, or defaults to the equator at the center of that time zone. If 
.B hcal
can't even retrieve time zone information from your computer, it defaults to Tel-Aviv. For other locations, use the 
.BI -l \ xx [ .xxx ]\ -L \ yy [ .yyy ]
option pair. For other timezones, use the 
.B -z
.I nn
option. Co-ordinates and standard time zones for some common locations are listed below.
.PP
The current defaults include:
.RS 9
Timezone   Default city    Lattitude  Longitude
.RE
.RS 12
-5      New York City      40        \-74
.RE
.RS 12
 0      London             51          0
.RE
.RS 12
 1      Paris              48          2
.RE
.RS 12
 2      Tel-Aviv           32         34
.RE
.RS 12
 3      Moscow             55         37
.RE
.PP
.B INPUTTING A HEBREW DATE:
If the year provided is greater than 3000,
.B hdate
will interpret the given date as a Hebrew date, and will display the calendar of the corresponding Gregorian month(s). Hebrew months are expected to be passed as numbers 1-12 for Tishrei - Elul; Adar I and Adar II are expected to be passed as months 13 and 14.
.PP 
.SH "OPTIONS"
.TP 18
.B \-3 --three-month
displays previous/next months, side by side. requires 127 columns.
.TP
.B \-c --colorize
displays in calming, muted tones
.TP
.B \-d --diaspora
use diaspora reading and holidays. Only relevant if hcal is using location information indicating an Israeli timezone
.TP
.B \-f --footnote
print descriptive notes of holidays
.TP
.B \-h --html
output in html format to stdout
.TP
.B \-H --hebrew
print Hebrew information in Hebrew
.TP
.B \-I --israel
override a diaspora default. Only relevant if hcal is using location information indicating other than an Israeli timezone
.TP
.B \-i    
use external css file "./hcal.css" for html output
.TP
.B \ \ \ \--no-reverse
do not highlight today's date
.TP
.B \-p --parasha
print week's parasha on each calendar row
.TP
.B \-s --shabbat
print Shabbat times and parshiot
.TP
.B \-l --latitude
xx[.xxx] degrees. Negative values are South
.TP
.B \-L --longitude
yy[.yyy] degrees.  Negative values are West
.TP
.B \-z --timezone
nn hours +/- UTC
.SH "HOLIDAYS"
.PP
Holidays are depicted by a change in the symbol separating a day's
Gregorian and Hebrew dates, as follows:
.RE
.RS 6
.B /
\ Regular day
.RE
.RS 6
.B +
\ Yom Tov (plus Yom Kippur)
.RE
.RS 6
.B *
\ Erev Yom Kippur
.RE
.RS 6
.B ~
\ Hol HaMoed
.RE
.RS 6
.B !
\ Hanuka and Purim
.RE
.RS 6
.B @
\ Tzomot
.RE
.RS 6
.B $
\ Lag BaOmer ,Tu BeAv, Tu BeShvat
.RE
.RS 6
.B #
\ Independance day and Yom Yerushalaim
.RE
.RS 6
.B %
\ Tzahal and Holocaust memorial days
.RE
.RS 6
.B ^
\ Other Israeli National days
.RE
.P
Use the -f / --footnote option to have hcal describe specifically what any particular day is marking.
.SH "BUGS"
.TP 10
.B Accuracy
The accuracy of the astronomically-derived data will suffer from not accounting for environmental conditions such as elevation, horizon, temperature and air pressure.
.TP
.B BIDI
In most locales, using option -H / --hebrew will cause hcal to output lines containing bi-directional text.
hcal conforms to the current unicode standards, and its output displays perfectly to any application that
accurately supports unicode/bidi. The rub is that, as of this writing, the only xterm clone I know that comes close is
.B mlterm
(version 3.0.8-2). Other xterm clones display the Hebrew text in reverse, although the output will paste well to other
applications (eg. mousepad, gedit, geany). The only deficiency noticeable when running hcal in mlterm is that calendar
header lines that begin with an LTR language, will justify the entire line right, while the lines of calendar body,
which begin with numerals, will justify right.
.P
.RS 10
An alternative is to pipe hcal's output through
.B fribidi
using the hcal option --no-reverse, but not using hcal's color option (you know, the "calming", "muted" tones).
.RE
.TP 10
.B TIMEZONES
The timezone support is currenlty primitive and lacks support for fractional time zone rules and  daylight savings
time transitions.
.SH "EXAMPLES"
.TP 3
1. Display a 2012ce year's calendar, three-months wide, in color.
.RS 6
.B       hcal -3c 2012
.RE
.HP 3
2. Display the current month's calendar, with Shabbat times, parshiot, footnoted holiday identification, with Hebrew information in Hebrew, and all in "calming", "muted" color-tones.
.RS 6
.B       hcal -csfH
.SH "SEE ALSO"
mlterm(1), fribidi(1), hdate(1), hebcal(1), date(1), cal(1), remind(1), hdate.h(3), hdate_struct(3)
.SH "AUTHORS"
.RS0
Boruch Baum 2011
.RE
Yaacov Zamir 2005-2010, text copied from Amos Shapir's hdate man file.
.PP
.B Hcal
and
.B Hdate
are part of the package
.B libhdate
, a small C/C++ library for Hebrew dates, holidays, and reading
sequences (parashiot). It uses the source code from Amos Shapir's
"hdate" package, as fixed and patched by Nadav Har'El. The Torah
reading sequence tables were contributed by Zvi Har'El.
