.\" .UC 4
.TH "hdate" "1" "2012-01-01" "Linux" "libhdate"
.SH "NAME"
hdate \- displays Hebrew date information for a given Gregorian/Julian date
.SH "SYNOPSIS"
.B hdate
[options] [coordinates [timezone]] [[[dd] mm] yyyy]
.P
.B hdate
[options] [coordinates [timezone]] [ julian_day ]
.TP
coordinates: -l [NS]yy[.yyy] -L [EW]xx[.xxx]
.RE
.RS 7
             -l [NS]yy[:mm[:ss]] -L [EW]xx[:mm[:ss]]
.RE
.RS 7
timezone:    -z nn[( .nn | :mm )]
.PP
.SH "DESCRIPTION"
.B hdate
translates the specified date to the Hebrew calendar and optionally displays further
information about that Hebrew date, including holidays and astronomical-related times
(see section LOCATIONS, below). If no arguments are given, it displays information for
the current date. If a single numeric argument is given, it will be interpreted as a
year, and 
.B hdate
will output the requested information for 
.I all 
days of that year. If two numeric arguments are given, it will be interpreted as mm yyyy, and
.B hdate
will output the requested information for 
.I all 
days of that month.
.PP 
.B INPUTTING A HEBREW DATE:
If the year provided is greater than 3000,
.B hdate
will interpret the given date as a Hebrew date, and will display information for the corresponding Gregorian date. Hebrew months are expected to be passed as numbers 1-12 for Tishrei - Elul; Adar I and Adar II are expected to be passed as months 13 and 14.
.PP
.B INPUTTING A JULIAN DAY:
If a single numeric argument is provided, and it is greater than 348021, 
.B hdate 
will interpret it as the "Julian day number" and will display information for the corresponding Hebrew date.
.PP 
.SH "OPTIONS"
.TP 18
.B \-b --bidi
output Hebrew information in Hebrew, but in reverse
.RE
.RS 7
.B \ \ \ --visual
\      sequence.
.TP 18
.B \-d --diaspora
force diaspora readings and holidays.
.RS 3
.B --israel
\      force Eretz Yisroel readings an holidays.
.RE
.TP
.B \ \ \ --daf-yomi
.TP
.B \-h --holidays
print holiday name if day is a holiday.
.TP
.B \-H 
Print only if day is a holiday, and print the holiday name.
.TP
.B \-i --ical 
use iCal formatted output.
.TP
.B \-j --julian
print Julian day number.
.TP
.B \-o --omer
print Sefirat Ha Omer, number of days only.
.RE
.RS 25
.B -oo
"today is n days in the omer"
.RE
.RS 25
.B -ooo
the full text, with weeks and remainder days
.RE
.RS 10
.B --ba-omer
\     full omer text, as 
.B -ooo
, in Hebrew
.RE
.RS 10
.B --la-omer
\     full omer text, as 
.B -ooo
, in Hebrew
.RE
.RS 7
.TP 18
.B \-q --quiet
suppress output, available in four levels. 
.B -q
suppresses warning messages, 
.B -qq
also suppresses the gregorian form of the requested Hebrew date, 
.B -qqq
suppresses labels for times of day,
.B -qqqq
suppresses the Hebrew date (useful if all one wants is some time-of-day information).
.TP
.B \-r --parasha
print weekly reading if day is Shabbat.
.TP
.B \-R 
print only if day is a Shabbat on which the regular weekly reading is read (ie. not a special holiday reading), and print that weekly reading.
.TP
.B \ \ \ --sun
print sunrise and sunset times.
.RE
.RS 7
.B \ \ \ --sunrise
.RE
.RS 7
.B \ \ \ --sunset
.TP 18
.B \-s --shabbat
print Shabbat start and end times. Use a specific long option to modify its default.
.RS 0
.B \ \ \ --shabbat-times
.RS 0
.B \ \ \ --candles
\     default is 20 minutes before sunset. (17<n<91)
.RS 0
.B \ \ \ --candle-lighting
.RS 0
.B \ \ \ --havdalah
\    default is 3 stars. (19<n<91 minutes)
.TP 18
.B \-S --short-format
print using short format.
.TP
.B \-t --times
print day times (three verbosity levels):
.RS 0
.B \ \ \ --times-of-day -t
\ \ first light, talit, sunrise, mid day, sunset,
.RS 0
.B \ \ \ --day-times
\ \ \ \ \ \ \ \ first stars, three stars,
.RE
.RS 23
and the length of that day's sun-hour.
.RE
.RS 18
.B -tt
\ adds end_Shema (GR"A), end_amidah,
.RE
.RS 23
mincha_gedola, mincha_ketana, plag_hamincha.
.RE
.RS 18
.B -ttt
adds end_Shema (M"A).
.P
Instead of using the presets, customize with:
.B --first-light --midday\ \ \ \ \ \ \ \ --shekia
.RS 0
.RE
.B --alot\ \ \ \ \ \ \ \ --noon\ \ \ \ \ \ \ \ \ \ --tzeit-hakochavim
.RS 0
.RE
.B --talit\ \ \ \ \ \ \ --chatzot\ \ \ \ \ \ \ --first-stars
.RS 0
.RE
.B --netz\ \ \ \ \ \ \ \ --mincha-gedola --three-stars
.RS 0
.RE
.B --shema\ \ \ \ \ \ \ --mincha-ketana --magen-avraham
.RS 0
.RE
.B --amidah\ \ \ \ \ \ --plag-hamincha --sun-hour

.RS 0
.RE
.B --sunrise\ \ \ \ \ --sunset
.RS 0
.RE
.B --end-eating-chometz-ma   --end-eating-chometz-gra
.RS 0
.RE
.B --end-owning-chometz-ma   --end-owning-chometz-gra
.RE
.TP 18
.B \-T --table
print tabular output. All data for each requested day
.RS 0
.B \ \ \ --tabular
\     will be output on a single comma-delimited line. Most
.RS 18
suitable for piping, or export to spreadsheets
.RE
.TP 18
.B \-l --latitude
[NS]yy[.yyy] decimal degrees, or [NS]yy[:mm[:ss]] degrees, minutes, seconds. Negative values are South
.TP
.B \-L --longitude
[EW]xx[.xxx] decimal degrees, or [EW]xx[:mm[:ss]] degrees, minutes, seconds. Negative values are West
.TP
.B \-z --timezone
\+/-UTC. Notation may  be in decimal hours ( hh[.hh] ) or hours, minutes ( hh[:mm] )
.TP
.B \ \   --hebrew
forces Hebrew to print in Hebrew characters
.TP
.B \ \   --yom
force Hebrew prefix to Hebrew day of week
.TP
.B \ \   --leshabbat
insert parasha between day of week and day
.TP
.B \ \   --leseder
insert parasha between day of week and day
.TP
.B \ \   --not-sunset-aware
don't display next day if after sunset
.SH NOTES
.SS LOCATIONS
If you want 
.B hdate
to display accurate time-of-day information,
.B hdate
requires location and time zone information in order to make astronomical calculations for a given date. If you don't provide ANY such information, 
.B hdate
tries to find out your computer's local time zone information as an indicator, and picks the 'primary' city in that time zone. If 
.B hdate
can't find local time zone information,
.B hdate
tries to find out your computer's GMT offset, and either picks from the list below the city in that time zone offset, or defaults to the equator at the center of that time zone offset. If 
.B hdate
can't even retrieve GMT offset information from your computer, it defaults to Tel-Aviv. For other locations, use the 
.B -l -L
option pair. For other timezones, use the 
.B -z
option. Co-ordinates and standard time zones for some common locations are listed below.
.PP
The current defaults are:
.RS 5
tz                 Lat    Lon      tz              Lat     Lon
.RE
.RS 5
-8   Los Angeles   34.05 -118.25    2    Tel-Aviv  32      34.75
.RE
.RS 5
-6   Mexico City   19.43  -99.13    3.5  Tehran    35.67   51.43
.RE
.RS 5
-5   New York City 40.75  -74       4    Moscow    55.75   37.62
.RE
.RS 5
-4.5 Caracas       10.54  -66.93    5    Tashkent  41.27   69.22
.RE
.RS 5
-3   Buenos Aires -34.61  -58.37    5.5  Calcutta  22.57   88.36
.RE
.RS 5
 0   London        51.5     0       8    Beijing   39.90  116.38
.RE
.RS 5
 1   Paris         48.86    2.34   10    Sydney   -33.87  151.21
.RE
.PP
Useful locations and time zones
.RS 6
2   Jerusalem     31.78   35.22    8   Hong Kong  22.26  114.15
.RE
.RS 6
2   Haifa         32.82   34.99   -6   Chicago    41.84  -87.67
.RE
.RS 6
2   Beer Sheva    31.25   34.80   -3   Sao Paolo -23.52  -46.63
.RE  
.RS 6
2   Ashdod        31.80   34.64   -5   Toronto    43.75  -79.38
.RS 6
.RE
2   Tiberias      40.89   35.84    1   Antwerpen  51.22    4.42
.RS 6
.RE
2   Eilat         29.56   34.95    3.5 Tehran     35.67   51.42
.SH FILES
.SS CONFIG FILE
This folder and file will be automatically created, and
includes its own documentation, in-line:
.RS 16
.I ${XDG_CONFIG_HOME}/hcal/hcalrc
.P
.RE
If ${XDG_CONFIG_HOME} is undefined:
.RS 16
.I ~/.config/hcal/hcalrc
.SH "BUGS"
.TP 10
.B Accuracy
The accuracy of the astronomically-derived data will suffer from not accounting for environmental conditions such as elevation, horizon, temperature and air pressure.
.RE
.TP 10
.B Timezones
The timezone support is currenlty primitive and lacks support for daylight savings time transitions.
.RE
.TP 10
.B Historical
The software does not yet account for the phenomenon and complications of the "Gregorian transition" from the prior, Julian calendar, which effectively caused an instantaneous 'loss' of two weeks for all gentiles affected. Countries (eg. Poland, Spain and Italy) began adopting the Gregorian calendar on 8 Tishrei 5343 (4 October 1582 CE), although many did not transition until the 56th century (1752 CE, eg. UK colonies, Sweden). Russia did not adopt the Gregorian calendar until 5678 (1918 CE) and Turkey did not until 5687 (December, 1926 CE). Many other countries made the transition on other dates. Keep in mind that Russia invaded part of Poland, undoing, for the interim, the Gregorian transition for (only) that part of Poland; Also important to remember in this regard is that Eretz Ysroel was part of the Turkish Ottoman empire until the British mandate (5677 (1917 CE)). Until all this is accounted for adequately by this application, refer to '
.B ncal -p
\' for a basic table of country transitions. However, keep in mind that European borders underwent many changes during the 426 years in question, so the accuracy of your data will depend on accurate knowledge of whether any particular date at any specific location was Julian or Gregorian.
.SH "EXAMPLES"
1. Create an iCal calendar of the holidays of year 2025.
.RS 6
.B       hdate -Hi 2025
.RE
.HP 3
2. Print out the weekly readings and sunset/sunrise times for Eilat, on April 2031 CE.
.RS  6  
.B       hdate -sR 4 2031 -l29 -L34 -z2
.RE
.SH "SEE ALSO"
mlterm(1), hcal(1), hebcal(1), date(1), ncal(1), cal(1), remind(1)
.SH "AUTHORS"
.RS 0
Boruch Baum 2011-2012. Yaacov Zamir 2005-2010.
.PP
project page: http://libhdate.sourceforge.net
.PP
.BR hcal \ and \ hdate
are part of the package
.B libhdate
, a small C/C++ library for Hebrew dates, holidays, and reading
sequences (parashiot). It uses the source code from Amos Shapir's
"hdate" package, as fixed and patched by Nadav Har'El. The Torah
reading sequence tables were contributed by Zvi Har'El.
