.\" .UC 4
.TH "HDATE" "1" "2011-11-21" "Linux" "libhdate"
.SH "NAME"
hdate \- displays Hebrew date information for a given Gregorian/Julian date
.SH "SYNOPSIS"
.B hdate
[\-soctShHrRjdiz]
.RI [\-l \ latitude \-L \ longitude ] 
[[[dd] mm] yyyy]

.B hdate
[\-soctShHrRjdiz] 
.RI [\-l \ latitude \-L \ longitude ] 
.RI [ julian_day ]
.PP
.SH "DESCRIPTION"
.B hdate
translates the specified date to the Hebrew calendar and optionally displays further information about that Hebrew date, including holidays and astronomical-related times.
If no arguments are given, it displays information for the current date. If a single numeric argument is given, it will be interpreted as a year, and 
.B hdate
will output the requested information for 
.I all 
days of that year. If two numeric arguments are given, it will be interpreted as mm yyyy, and
.B hdate
will output the requested information for 
.I all 
days of that month.
.PP
.B LOCATION: hdate
requires location and time zone information in order to make astronomical calculations for a given date. If you don't provide ANY such information, 
.B hdate
uses your computer's local time zone information as an indicator, and either picks a city in that time zone, or defaults to the equator at the center of that time zone. If 
.B hdate
can't even retrieve time zone information from your computer, it defaults to Tel-Aviv. For other locations, use the 
.BI -l \ xx [ .xxx ]\ -L \ yy [ .yyy ]
option pair. For other timezones, use the 
.B -z
.I nn
option. Co-ordinates and standard time zones for some common locations are listed below.
.PP
The current defaults are:
.RS 9
Timezone   Default city    Lattitude  Longitude
.RE
.RS 12
-5      New York City      40        \-74
.RE
.RS 12
 0      London             51          0
.RE
.RS 12
 1      Paris              48          2
.RE
.RS 12
 2      Tel-Aviv           32         34
.RE
.RS 12
 3      Moscow             55         37
.RE
.PP 
.B INPUTTING A HEBREW DATE:
If the year provided is greater than 3000,
.B hdate
will interpret the given date as a Hebrew date, and will display information for the corresponding Gregorian date. Hebrew months are expected to be passed as numbers 1-12 for Tishrei - Elul; Adar I and Adar II are expected to be passed as months 13 and 14.
.PP
.B INPUTTING A JULIAN DAY:
If a single numeric argument is provided, and it is greater than 348021, 
.B hdate 
will interpret it as the "Julian day number" and will display information for the corresponding Hebrew date.
.PP 
.SH "OPTIONS"
.TP 6
.B \-s
Print sunrise/sunset times.
.TP 6
.B \-c
Print Shabat start/end times. Shabat starts 20 min before sunset, 
and ends when three stars are out. 
.TP 6
.B \-t
Print day times list: first light, talit, sunrise, mid day, sunset, first stars, three stars. 
.TP 6
.B \-S 
Print using short format.
.TP 6
.B \-h 
Print holidays.
.TP 6
.B \-o 
Print Sfirat Ha Omer.
.TP 6
.B \-H 
Print just holidays.
.TP 6
.B \-r 
Print weekly reading on Saturday.
.TP 6
.B \-R 
Print just weekly reading on Saturday.
.TP 6
.B \-j 
Print Julian day number.
.TP 6
.B \-d 
Use diaspora reading and holidays.
.TP 6
.B \-i 
Use iCal formatted output.
.P
.BI \-l \ xx
.RI latitude \ xx [ .xxx ]
degrees. Negative values are South.
.P
.BI \-l \ yy
.RI longitude \ yy [ .yyy ]
degrees.  Negative values are West.
.P
.BI \-z \ nn
timezone +/- UTC
.SH "BUGS"
.PP
The accuracy of the astronomically-derived data will suffer from not accounting for environmental conditions such as elevation, horizon, temperature and air pressure.
.PP
The timezone support is primitive and lacks support for fractional time zone rules and  daylight savings time transitions. 
.SH "EXAMPLES"
1. Create an iCal calendar of the holidays of year 2025.
.RS 6
.B       hdate -Hi 2025
.RE
.HP 3
2. Print out the weekly readings and sunset/sunrise times for Eilat, on April 2031.
.RS  6  
.B       hdate -sR 4 2031 -l29 -L34 -z2
.RE
.SH Useful locations and time zones
.RS 6
Jerusalem   31, 35, 2      New York  40, \-74, -5
.RE
.RS 6
Tel Aviv    32, 34, 2      London    51,   0,  0
.RE
.RS 6
Haifa       32, 34, 2      Paris     48,   2,  1
.RE
.RS 6
Beer Sheva  31, 34, 2      Moscow    55,  37,  3
.RE
.RS 6
Ashdod      31, 34, 2
.RS 6
.RE
Tiberias    32, 35, 2
.RS 6
.RE
Eilat       29, 34, 2

.SH "SEE ALSO"
date(1), cal(1), hcal(1), hebcal(1), remind(1), hdate.h(3), hdate_struct(3)
.SH "AUTHORS"
.RS 0
Boruch Baum 2011. Yaacov Zamir 2005-2010. Text copied from Amos Shapir's hdate man file.
.PP
.BR hcal \ and \ hdate
are part of the package
.B libhdate
, a small C,C++ library for Hebrew dates, holidays, and reading
sequences (parashiot). It uses the source code from Amos Shapir's
"hdate" package, as fixed and patched by Nadav Har'El. The Torah
reading sequence tables were contributed by Zvi Har'El.
