.\" .UC 4
.TH "HDATE" "1" "2011-11-21" "Linux" "libhdate"
.SH "NAME"
hdate \- displays Hebrew date information for a given Gregorian/Julian date
.SH "SYNOPSIS"
.B hdate
[options]
.RI [\-l \ latitude \ \-L \ longitude \ [-z \ nn ]]
[[[dd] mm] yyyy]

.B hdate
[options]
.RI [\-l \ latitude \ \-L \ longitude \ [-z \ nn ]]
.RI [ julian_day ]
.PP
.SH "DESCRIPTION"
.B hdate
translates the specified date to the Hebrew calendar and optionally displays further information about that Hebrew date, including holidays and astronomical-related times.
If no arguments are given, it displays information for the current date. If a single numeric argument is given, it will be interpreted as a year, and 
.B hdate
will output the requested information for 
.I all 
days of that year. If two numeric arguments are given, it will be interpreted as mm yyyy, and
.B hdate
will output the requested information for 
.I all 
days of that month.
.PP
.B LOCATION: 
If you want 
.B hdate
to display accurate time-of-day information,
.B hdate
requires location and time zone information in order to make astronomical calculations for a given date. If you don't provide ANY such information, 
.B hdate
uses your computer's local time zone information as an indicator, and either picks a city in that time zone, or defaults to the equator at the center of that time zone. If 
.B hdate
can't even retrieve time zone information from your computer, it defaults to Tel-Aviv. For other locations, use the 
.BI -l \ xx [ .xxx ]\ -L \ yy [ .yyy ]
option pair. For other timezones, use the 
.B -z
.I nn
option. Co-ordinates and standard time zones for some common locations are listed below.
.PP
The current defaults include:
.RS 9
Timezone   Default city    Lattitude  Longitude
.RE
.RS 12
-5      New York City      40        \-74
.RE
.RS 12
 0      London             51          0
.RE
.RS 12
 1      Paris              48          2
.RE
.RS 12
 2      Tel-Aviv           32         34
.RE
.RS 12
 3      Moscow             55         37
.RE
.PP 
.B INPUTTING A HEBREW DATE:
If the year provided is greater than 3000,
.B hdate
will interpret the given date as a Hebrew date, and will display information for the corresponding Gregorian date. Hebrew months are expected to be passed as numbers 1-12 for Tishrei - Elul; Adar I and Adar II are expected to be passed as months 13 and 14.
.PP
.B INPUTTING A JULIAN DAY:
If a single numeric argument is provided, and it is greater than 348021, 
.B hdate 
will interpret it as the "Julian day number" and will display information for the corresponding Hebrew date.
.PP 
.SH "OPTIONS"
.TP 6
.B \-c
print Shabbat start/end times. Shabbat starts 20 min before sunset, 
and ends when three stars are out. 
.TP 6
.B \-d 
use diaspora reading and holidays.
.TP 6
.B \-h 
print holidays.
.TP 6
.B \-H 
Print just holidays.
.TP 6
.B \-i 
use iCal formatted output.
.TP 6
.B \-j 
print Julian day number.
.TP 6
.B \-o 
print Sefirat Ha Omer.
.TP 6
.B \-q
quiet. suppress warning messages
.TP 6
.B \-r 
print weekly reading on Saturday.
.TP 6
.B \-R 
print just weekly reading on Saturday.
.TP 6
.B \-s
print sunrise/sunset times.
.TP 6
.B \-S 
print using short format.
.TP 6
.B \-t
print day times list: first light, talit, sunrise, mid day, sunset, first stars, three stars. 
.TP
.B \-l --latitude
xx[.xxx] degrees. Negative values are South.
.TP
.B \-L --longitude
yy[.yyy] degrees.  Negative values are West.
.TP
.B \-z --timezone
nn hours +/- UTC
.SH "BUGS"
.TP 10
.B Accuracy
The accuracy of the astronomically-derived data will suffer from not accounting for environmental conditions such as elevation, horizon, temperature and air pressure.
.TP
.B BIDI
In most locales, using option -H / --hebrew will cause hcal to output lines containing bi-directional text.
hcal conforms to the current unicode standards, and its output displays perfectly to any application that
accurately supports unicode/bidi. The rub is that, as of this writing, the only xterm clone I know that comes close is
.B mlterm
(version 3.0.8-2). Other xterm clones display the Hebrew text in reverse, although the output will paste well to other
applications (eg. mousepad, gedit, geany). The only deficiency noticeable when running hcal in mlterm is that calendar
header lines that begin with an LTR language, will justify the entire line right, while the lines of calendar body,
which begin with numerals, will justify right.
.P
.RS 10
An alternative is to pipe hcal's output through
.B fribidi
using the hcal option --no-reverse, but not using hcal's color option (you know, the "calming", "muted" tones).
.RE
.TP 10
.B TIMEZONES
The timezone support is currenlty primitive and lacks support for fractional time zone rules and  daylight savings
time transitions.
.SH "EXAMPLES"
1. Create an iCal calendar of the holidays of year 2025.
.RS 6
.B       hdate -Hi 2025
.RE
.HP 3
2. Print out the weekly readings and sunset/sunrise times for Eilat, on April 2031.
.RS  6  
.B       hdate -sR 4 2031 -l29 -L34 -z2
.RE
.SH Useful locations and time zones
.RS 6
Jerusalem   31, 35, 2      New York  40, \-74, -5
.RE
.RS 6
Tel Aviv    32, 34, 2      London    51,   0,  0
.RE
.RS 6
Haifa       32, 34, 2      Paris     48,   2,  1
.RE
.RS 6
Beer Sheva  31, 34, 2      Moscow    55,  37,  3
.RE
.RS 6
Ashdod      31, 34, 2
.RS 6
.RE
Tiberias    32, 35, 2
.RS 6
.RE
Eilat       29, 34, 2

.SH "SEE ALSO"
mlterm(1), fribidi(1), hcal(1), hebcal(1), date(1), cal(1), remind(1), hdate.h(3), hdate_struct(3)
.SH "AUTHORS"
.RS 0
Boruch Baum 2011. Yaacov Zamir 2005-2010. Text copied from Amos Shapir's hdate man file.
.PP
.BR hcal \ and \ hdate
are part of the package
.B libhdate
, a small C/C++ library for Hebrew dates, holidays, and reading
sequences (parashiot). It uses the source code from Amos Shapir's
"hdate" package, as fixed and patched by Nadav Har'El. The Torah
reading sequence tables were contributed by Zvi Har'El.
